### PR TITLE
Switch to updated codecov action

### PR DESCRIPTION
**Pull request by znicholls**
## Checklist

Please confirm that this pull request has done the following:

~- [ ] Tests added~
~- [ ] Documentation added (where applicable)~
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by znicholls** [comment]
@lewisjared if you make me an admin of this repo I can add the token. Alternately you can follow the docs here https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage and add the code cov token secret then the code cov integration should work

**Comment by lewisjared** [comment]
Thanks. I need my Yubikey to do that so I'll set that up once I'm home

**Comment by znichollscr** [comment]
@lewisjared ping here

**Review by lewisjared — APPROVED** [review]
Thanks. I added the secret as I couldn't figure out how to make you an admin.

**Pull request merged**
